### ISSUE TITLE
Needed versioning for AltStore repo

### ISSUE THREAD

**Issue by noah978** [Wh0ba/XPatcher#1]
Hello,

I was hoping to add XPatcher to my AltStore repositiory: https://quarksources.imfast.io

But I noticed in your info.plist, the ``CFBundleShortVersionString`` is listed as 1.0.0 on your v1.1 release. I figured I should mention sooner rather than later that AltStore currently relies on the changes in the IPAs ``CFBundleShortVersionString`` to know when to push updates.

For future releases, I'd recommend making sure that you keep internal versioning system working so that I can potentially push future updates to existing users without any issues.

Thanks!

**Comment by Wh0ba** [comment]
Oh thanks for the heads up,
I didn't really look into the `info.pist` for such properties since I didn't think they matter much.
But I'll keep it in mind next release 

And I'll change it in the current release and update the ipa file
