### ISSUE TITLE
Crashes everytime I try to patch

### ISSUE THREAD

**Issue by EugeneBob** [Wh0ba/XPatcher#4]
Everytime I click on the rom or patch file the app crashes. I’ve installed it via .deb and jailbroken on iPadOS 14.4

**Comment by Wh0ba** [comment]
Can you provide the crash logs ? (mostly generated by Crash Reported or Cr4shed)
does  side load it as an ipa and patching  work for you ?

**Comment by Wh0ba** [comment]
Also I've tried to reproduce the bug, but it didn't occur
Steps:
```
  Installed XPatcher deb through Filza
  ran uicache -p /Applications/XPatcher.app/
  added the rom and the patch files inside "/var/mobile/Documents/"
  selected them (no crash occurred)
  applied the patch successfully 
```

**Comment by EugeneBob** [comment]
![688A77F7-FA1D-4D61-A165-74ABBD6B86D5](https://user-images.githubusercontent.com/88921038/129458700-b5fc5518-bd0e-4833-ad54-5689d897db81.png)
[text.txt](https://github.com/Wh0ba/XPatcher/files/6987114/text.txt)

**Comment by Wh0ba** [comment]
Hmmmm, interesting
Can you please check if this crash/error occurs when changing patch types in the create mode ? 
since that also uses an action sheet which from what I understand requires extra code on the iPad to prevent the crash, and thanks for your kind help 😊

**Comment by EugeneBob** [comment]
If you mean the “mode” on the top left, this happens
[text.txt](https://github.com/Wh0ba/XPatcher/files/6987174/text.txt)
![9507B283-E295-4BCA-8D0D-DED1D544A251](https://user-images.githubusercontent.com/88921038/129459552-5d4300bf-ebf4-47cf-9e74-ba43739e2dc8.png)

**Comment by EugeneBob** [comment]
But if I use the patch file, this happens
![AA5B0A8C-12B7-4944-9D9E-7DC5C1F22A50](https://user-images.githubusercontent.com/88921038/129459579-ab640435-cffb-454a-9a81-786aab97d2cd.png)
[text.txt](https://github.com/Wh0ba/XPatcher/files/6987176/text.txt)

**Comment by Wh0ba** [comment]
I think I squashed this bug just now, can you please test it if you have time 
https://www.dropbox.com/s/zemn91xrs96solj/com.wh0ba.xpatcher_2.0-2%2Bdebug_iphoneos-arm.deb?dl=1
here's the .deb
And again thanks for your feedback 😊

**Comment by EugeneBob** [comment]
Yup, everything is working, thx for your hard work!
