### ISSUE TITLE
Display Hashes of ROM files

### ISSUE THREAD

**Issue by lonkelle** [Wh0ba/XPatcher#5]
It would be helpful to add these calculations to the app whenever you input a ROM file. 

![85AA1832-B259-41D4-962A-1C806608F2FC](https://user-images.githubusercontent.com/5572600/148306500-032d06a7-afe1-4828-85a0-a00d8c18abac.jpeg)

**Comment by Wh0ba** [comment]
Hey there thanks for the feedback, I've just added this feature to show SHA1, MD5, and CRC32 hashes whenever you select a file in the Documents tab
